2020-04-01 18:07:23 = INFO - [settings.py] BASE_DIR set to /home/ryan/Desktop/SFU/CSSS_Site/csss-site/csss-site/src
2020-04-01 18:07:23 = INFO - [settings.py] DEBUG set to True
2020-04-01 18:07:23 = INFO - [settings.py] HOST_ADDRESS set to *
2020-04-01 18:07:23 = INFO - [settings.py] ALLOWED_HOSTS set to ['*']
2020-04-01 18:07:23 = INFO - [settings.py] ROOT_DIR set to /home/ryan/Desktop/SFU/CSSS_Site/csss-site
2020-04-01 18:07:23 = INFO - [settings.py] STATIC_URL set to /STATIC_URL/
2020-04-01 18:07:23 = INFO - [settings.py] STATIC_ROOT set to /home/ryan/Desktop/SFU/CSSS_Site/csss-site/csss-site/src/static_root/
2020-04-01 18:07:23 = INFO - [settings.py] MEDIA_URL set to /MEDIA_URL/
2020-04-01 18:07:23 = INFO - [settings.py] MEDIA_ROOT set to /home/ryan/Desktop/SFU/CSSS_Site/csss-site/csss-site/src/media_root/
2020-04-01 18:07:23 = INFO - [settings.py] FILE_FORM_MASTER_DIR set to form_uploads/form_uploads/
2020-04-01 18:07:23 = INFO - [settings.py] FILE_FORM_UPLOAD_DIR set to form_uploads/form_uploads/temporary_files/
2020-04-01 18:07:23 = INFO - [settings.py] DJANGO_MAILBOX_ATTACHMENT_UPLOAD_TO set to mailbox_attachments/%Y/%m/%d/
2020-04-01 18:07:23 = WARNING - Watching for file changes with StatReloader

2020-04-01 18:07:23 = INFO - Performing system checks...


2020-04-01 18:07:23 = INFO - System check identified no issues (0 silenced).

2020-04-01 18:07:23 = INFO - April 01, 2020 - 18:07:23

2020-04-01 18:07:23 = INFO - Django version 2.2.10, using settings 'csss.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

2020-04-01 18:07:27 = INFO - sitting on da bus
2020-04-01 18:07:27 = INFO - using da comic sans
2020-04-01 18:07:27 = INFO - doing somit
2020-04-01 18:07:27 = INFO - doin nother ting
2020-04-01 18:07:27 = WARNING - Internal Server Error: /documents/photo_gallery/Frosh Fun/2020-04-01
Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'media.id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/.local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ryan/Desktop/SFU/CSSS_Site/csss-site/csss-site/src/documents/views.py", line 107, in album
    return render(request, 'documents/album.html', context)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/defaulttags.py", line 952, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/ryan/.local/lib/python3.7/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 26: 'media.id', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?

2020-04-01 18:07:27 = WARNING - [01/Apr/2020 18:07:27] "GET /documents/photo_gallery/Frosh%20Fun/2020-04-01 HTTP/1.1" 500 207523

